---

- name: Install Nginx
  package:
    name: "{{ nginx_package }}"
    state: present

- name: Start Nginx web server
  service:
    name: nginx
    state: started

- name: Copy Nginx sites-available file
  template:
    src: nginxc.conf.j2
    dest: /etc/nginx/sites-available/default
  
- name: Enable Nginx virtual host
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify:
    - Restart Nginx

- name: Restart Nginx web server
  service:
    name: nginx
    state: reloaded


