---

- name: Install Nginx
  package:
    name: "{{ nginx_package }}"
    state: present

- name: Start Nginx web server
  service:
    name: nginx
    state: started

- name: Copy Nginx sites-available file
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/nginxc.conf.j2
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart Nginx
  

- name: Enable Nginx virtual host
  file:
    src: /etc/nginx/sites-available/nginxc.conf.j2
    dest: /etc/nginx/sites-enabled/nginxc.conf.j2
    state: link
  notify:
    - Restart Nginx

