---
# tasks file for git

- name: Install Git package
  package:
    name: git
    state: present

- name: Clone git repository
  git:
    repo: https://github.com/mdshihabuddin10/locallib.git
    dest: /home/shi/pro

